### ISSUE TITLE
Include authors ORCID at dataset

### ISSUE THREAD

**Issue by pablovp86** [lepidus/dataversePlugin#22]
As an author
I want the contributors ORCID, present on the submission, to be present into the dataset
So that they can be uniquely identified

Here is an example of a dataset submitted manually to the Dataverse with authors ORCID, for inspiration:
https://data.scielo.org/dataset.xhtml?persistentId=doi:10.48331/scielodata.NWUMDI

**Comment by alexxxmendonca** [comment]
This would be great, but in the example you've given, the ORCID IDs were added using free text, right?

Are you suggesting an authenticated way of adding ORCIDs?

**Comment by pablovp86** [comment]
> This would be great, but in the example you've given, the ORCID IDs were added using free text, right?

Yes. In Dataverse there is an author identifier type selection, and a free text field (ORCID is not validated).

![Captura de tela de 2022-12-07 19-30-34](https://user-images.githubusercontent.com/26493682/206444263-3f79b85b-b885-4143-88f7-4c73453fe8ab.png)

>Are you suggesting an authenticated way of adding ORCIDs?

The idea is to copy the contributors ORCIDs from the submission (when it is present).  On OPS/OJS side there is ORCID validation.

![screenshot-localhost_8080-2022 12 08-08_54_12](https://user-images.githubusercontent.com/26493682/206445076-1160baf5-2a8b-4775-8801-6bc76ea3c9d6.png)

I updated the story description, to make it clearer.

**Comment by alexxxmendonca** [comment]
I see! Thanks for clarifying!

**Comment by pablovp86** [comment]
[Release](https://github.com/lepidus/dataversePlugin/releases/tag/v1.4.7).
